# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: #welcome
    weight: 10
  - name: About
    url: about
    weight: 20
  - name: People
    url: people
    weight: 30
  - name: Activities
    url: event
    weight: 40
  - name: Media
    url: media
    weight: 50
  - name: Research
    url: https://pure.itu.dk/portal/en/organisations/center-for-digital-play
    weight: 60
  - name: Education
    url: education
    weight: 70
  - name: Contacts
    url: contact
    weight: 80
